#### Some common terms to remember
1. corpus
2. vocubulary
3. document
4. Word


### Bag of words

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({"text":["people watch dswithharry",
                           "dswithharry watch dswithharry",
                           "people write comment",
                           "dswithharry write comment"],
                           "output":[1,1,0,0]})
df 

text  output
0       people watch dswithharry       1
1  dswithharry watch dswithharry       1
2           people write comment       0
3      dswithharry write comment       0

In [5]:
## count vectorizer is Bag of Word Technique
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [6]:
bow = cv.fit_transform(df['text'])

In [7]:
## Vocabulary
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'dswithharry': 1, 'write': 4, 'comment': 0}


In [9]:
bow.toarray()

array([[0, 1, 1, 1, 0],
       [0, 2, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [1, 1, 0, 0, 1]])

In [11]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())
print(bow[3].toarray())


[[0 1 1 1 0]]
[[0 2 0 1 0]]
[[1 0 1 0 1]]
[[1 1 0 0 1]]


In [12]:
# new
cv.transform(['arvind watch dsawithharry']).toarray()

array([[0, 0, 0, 1, 0]])

In [13]:
X = bow.toarray()
y = df['output']


### N-grams

In [15]:
df = pd.DataFrame({"text":["people watch dswithharry",
                           "dswithharry watch dswithharry",
                           "people write comment",
                           "dswithharry write comment"],
                           "output":[1,1,0,0]})
df 

text  output
0       people watch dswithharry       1
1  dswithharry watch dswithharry       1
2           people write comment       0
3      dswithharry write comment       0

In [17]:
## Bi grams
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(2,2))

In [18]:
bow = cv.fit_transform(df['text'])

In [19]:
print(cv.vocabulary_)

{'people watch': 2, 'watch dswithharry': 4, 'dswithharry watch': 0, 'people write': 3, 'write comment': 5, 'dswithharry write': 1}


In [20]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[0 0 1 0 1 0]]
[[1 0 0 0 1 0]]
[[0 0 0 1 0 1]]


In [21]:
### Tri grams
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(3,3))


In [22]:
bow = cv.fit_transform(df['text'])

In [23]:
print(cv.vocabulary_)

{'people watch dswithharry': 2, 'dswithharry watch dswithharry': 0, 'people write comment': 3, 'dswithharry write comment': 1}


In [24]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[0 0 1 0]]
[[1 0 0 0]]
[[0 0 0 1]]


### TF-IDF (Term Frequency - Inverse Document Frequency)

In [25]:
df = pd.DataFrame({"text":["people watch dswithharry",
                           "dswithharry watch dswithharry",
                           "people write comment",
                           "dswithharry write comment"],
                           "output":[1,1,0,0]})
df 

text  output
0       people watch dswithharry       1
1  dswithharry watch dswithharry       1
2           people write comment       0
3      dswithharry write comment       0

In [27]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()

In [28]:
arr = tfidf.fit_transform(df['text']).toarray()

In [29]:
arr

array([[0.        , 0.49681612, 0.61366674, 0.61366674, 0.        ],
       [0.        , 0.8508161 , 0.        , 0.52546357, 0.        ],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.57735027],
       [0.61366674, 0.49681612, 0.        , 0.        , 0.61366674]])

In [30]:
print(tfidf.idf_)

[1.51082562 1.22314355 1.51082562 1.51082562 1.51082562]


#### word2vec, Transformer based techniques are better 